name: Multiple browsers and platforms workflow
run-name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write

jobs:
  build_and_test:
    defaults:
      run:
        shell: bash
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [chrome, firefox]
        java_version: [17]
    runs-on: ${{ matrix.os }}
    name: ${{ join(matrix.*, '_') }}
    env:
      MATRIX_JOB_NAME: ${{ join(matrix.*, '_') }}

    steps:
      - name: "[Prepare] Checkout"
        uses: actions/checkout@v3

      - name: "[Prepare] Setup JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}

      - name: "[Prepare] Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "[Test] Execute"
        id: test_execution
        run: ./gradlew clean test
        env:
          browser: ${{ matrix.browser }}
          isRemote: true

      - if: success() || failure()
        name: "[Report] JUnit report"
        uses: mikepenz/action-junit-report@v4
        with:
          check_name: JUnit ${{ env.MATRIX_JOB_NAME }}
          report_paths: build/test-results/test/TEST-*.xml

      - if: steps.test_execution.conclusion == 'failure'
        name: "[Artifact] Test Results"
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ env.MATRIX_JOB_NAME }}
          path: build/reports/tests/test

      - name: "[Report] Generate Allure Report"
        if: always()
        uses: allure-framework/allure-github-actions@v2
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report-${{ env.MATRIX_JOB_NAME }}
          allure_history: allure-history

      - name: "[Pages] Setup"
        if: always()
        uses: actions/configure-pages@v2

      - name: "[Pages] Upload artifact"
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: allure-history

      - name: "[Pages] Deploy"
        if: always()
        uses: actions/deploy-pages@v1 